shell = "zsh"

# --- 1. Core Utilities ---
[plugins.zsh-sudo]
github = "hcgraf/zsh-sudo"

[plugins.zsh-z]
github = "agkozak/zsh-z"

[plugins.fzf-arch]
inline = 'source /usr/share/fzf/key-bindings.zsh && source /usr/share/fzf/completion.zsh'

# --- 2. Visuals & Completion ---
# Inline templates allow us to control load order precisely
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["source"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["source"]

[plugins.zsh-you-should-use]
github="MichaelAquilina/zsh-you-should-use"

# --- 3. Theme (Powerlevel10k) ---
[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.omz-git]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/git"

[plugins.omz-common-aliases]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/common-aliases"

# [plugins.zsh-autocomplete] 
# github="marlonrichert/zsh-autocomplete"

# 1. Rust (Cargo shortcuts)
[plugins.omz-rust]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/rust"

# 2. NPM (Node shortcuts)
[plugins.omz-npm]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/npm"

[plugins.omz-extract]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/extract"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.omz-colored-man-pages]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/colored-man-pages"

[plugins.omz-lib]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["functions.zsh"]

[plugins.omz-web-search]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/web-search"

[plugins.omz-docker]
github = "ohmyzsh/ohmyzsh"
dir = "plugins/docker"

